- frontend/src/App.tsx
- frontend/src/Component/Header/index.tsx
- frontend/tsconfig.json
분업을 위한 구조 잡기 및 Header 마크업(진행 중)
> feat: Header 마크업

- frontend/src/App.tsx
- frontend/src/components/login/index.tsx
- frontend/src/components/register-puzzle/index.tsx
- frontend/src/styles/global-style.tsx
global-style.tsx를 App.tsx에 넣어서 전역으로 활용
register-puzzle/index.tsx style 리팩토링
> style:style 태그 리팩토링

- backend/api/index.ts
- backend/api/search/search.ts
- backend/services/db/searchService.ts
- backend/services/db/userService.ts
- backend/services/search-service.ts
> feat:메인 페이지 퍼즐 보여주는 API

- backend/services/db/puzzle-service.ts
- backend/services/search-service.ts
> feat:조회수 정렬

- frontend/src/components/puzzle-canvas/index.tsx
- frontend/src/components/puzzle-canvas/puzzle/index.tsx
- frontend/src/pages/play-puzzle/index.tsx
> Feat: 퍼즐 타일 생성 및 무작위 배치

- frontend/src/components/puzzle-canvas/puzzle/index.tsx
> fix: 퍼즐 타일 순서 수정

- frontend/src/components/puzzle-canvas/index.tsx
- frontend/src/components/puzzle-canvas/puzzle/index.tsx
- frontend/src/pages/play-puzzle/index.tsx
> Feat: puzzle move

- frontend/src/components/puzzle-canvas/index.tsx
- frontend/src/pages/play-puzzle/index.tsx
* 기존 가로 길이 기준에서 가로 세로 중 긴 쪽 기준으로 변경
> feat: 퍼즐 난이도 기준 변경

- frontend/src/components/kakao-share-btn/index.tsx
* 여러번 initialize하게 되어 생긴 문제
* 조건문으로 한번만 initialize하게 해서 해결
> fix: 카카오 공유 initialize 에러 문제 해결

- frontend/src/components/chat/index.tsx
- frontend/src/components/level-component/index.tsx
- frontend/src/pages/play-puzzle/index.tsx
- frontend/src/pages/register-puzzle/index.tsx
> fix: chat css 수정, setPuzzle 호출방식 수정, register 레벨 컴포넌트 수정

- backend/services/play-puzzle.ts
- backend/services/roomInfo.ts
- backend/services/socket-service.ts
- frontend/src/components/chat/index.tsx
- frontend/src/components/header/index.tsx
- frontend/src/context/socket.tsx
- frontend/src/pages/play-puzzle/index.tsx
- 소켓 관리 방식 변경(useContext 사용)
- 타이머 추가
- 채팅에 유저 id 출력
> play puzzle 페이지 작업

- backend/services/socket-service.ts
- frontend/src/components/play-puzzle/puzzle-canvas/index.tsx
- frontend/src/pages/play-puzzle/index.tsx
join시 첫번째 client라면 서버에서 emit("firstClient")
> feat: play-Room의 첫 번째 client인지 확인

- backend/services/socket-service.ts
- frontend/src/components/play-puzzle/puzzle-canvas/index.tsx
- frontend/src/components/play-puzzle/puzzle-canvas/puzzle/move-puzzle.tsx
mouseUp 이벤트에선 changeData를 config 자체로 보냄
> fix: 클라이언트-서버 퍼즐 정보 동기화

- backend/services/socket-service.ts
- frontend/src/pages/play-puzzle/index.tsx
- 조회수+2 오류 수정: 프론트의 getPuzzleInfo 호출시 조건문 추가
- playRoom 비로그인 유저 접근 관리: 조건문 추가
> fix: 조회수 오류 수정, playRoom 비로그인 유저 접근 관리

- frontend/src/components/play-puzzle/chat/index.tsx
1. 채팅 소켓 off 추가
2. 최신 채팅 대화에 스크롤이 내려가도록 기능 추가
> Fix&feat: chat

- frontend/src/components/play-puzzle/puzzle-canvas/puzzle/move-puzzle.tsx
- 기존에 퍼즐이 생성되면 중앙에 위치하지 않고 치우쳐 있던 문제 해결
> fix: puzzle 위치 조정

- frontend/src/pages/mypage/index.tsx
> chore: mypage css 수정

- frontend/src/components/play-puzzle/chat/index.tsx
- frontend/src/components/play-puzzle/puzzle-canvas/index.tsx
- frontend/src/components/play-puzzle/puzzle-canvas/puzzle/complete-animation.tsx
- frontend/src/components/play-puzzle/puzzle-canvas/puzzle/move-puzzle.tsx
- 채팅 z-index 추가
- 레벨 1단계 300 => 400으로 수정
- completet animation이 재생되는 레이어 분리
> fix: complete animation

- backend/services/socket-service.ts
- frontend/src/components/common/header/index.tsx
- 60초가 뜬 후에 1분으로 변경되던 문제 해결
- date.now()로 시간 기준 변경
> fix: timer

- backend/services/register-puzzle-service.ts
> Fix: register puzzle keyword

- frontend/src/components/logo-canvas/index.tsx
> feat: 이스터에그 추가 및 퍼즐 조각 떨림 수정

- backend/services/socket-service.ts
- frontend/src/components/play-puzzle/puzzle-canvas/index.tsx
- frontend/src/components/play-puzzle/puzzle-canvas/puzzle/index.tsx
- frontend/src/components/play-puzzle/puzzle-canvas/puzzle/move-puzzle.tsx
> fix: mouseUp 후 타일 이동 socket 통신이 되도록 수정

- frontend/src/components/common/image-card/index.tsx
- frontend/src/pages/login/index.tsx
- frontend/src/pages/play-puzzle/index.tsx
- frontend/src/pages/warning/index.tsx
warning 경고창에서 시작페이지로 이동해 로그인한 경우, 다시 해당 퍼즐 플레이 페이지로 이동
메모리 누수 오류가 있음
> feat: 비로그인 유저 퍼즐진입 후 재진입

- backend/services/socket-service.ts
- frontend/src/components/common/header/index.tsx
- frontend/src/components/play-puzzle/puzzle-canvas/index.tsx
- frontend/src/pages/play-puzzle/index.tsx
- 기존의 setInterval을 사용한 방식은 사용자끼리 시간에 차이가 나고
브라우가 inactive하면 정확한 값을 측정할 수 없는 문제가 있었다.
- setInterval을 100ms마다 호출해서 Date.now()로 시간을 측정하는 방식으로
변경
> feat: 정확한 타이머 구현

- frontend/src/pages/login/index.tsx
- frontend/src/pages/play-puzzle/index.tsx
- frontend/src/pages/warning/index.tsx
- login/index.에 빠진 코드 수가
- Link 대신 button으로 돌아가기 기능 출력
> fix: 비로그인 접근 후 퍼즐 재진입 수정
